In [3]:
import sys
!{sys.executable} -m pip install pandas
import import_ipynb
import glassdoor_scrapper as gs
import pandas as pd

path = '/usr/bin/safaridriver'

df = gs.get_jobs('data_scientist',10,False,path,15)

display(df)

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (1.2.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pandas) (2.8.1)
Requirement already satisfied: numpy>=1.16.5 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pandas) (1.19.4)
Requirement already satisfied: pytz>=2017.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pandas) (2020.5)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
 x out failed
Progress: 0/10
Progress: 1/10
Progress: 2/10
Progress: 3/10
Progress: 4/10
Progress: 5/10
Progress: 6/10
Progress: 7/10
Progress: 8/10
Progress: 9/10
Progress: 10/10

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,Data Scientist 2,$52K - $95K (Glassdoor est.),Description\nDigital Health and Analytics with...,3.9,Humana3.9,"Louisville, KY",-1,-1,-1,-1,-1,-1,-1,-1
1,Data Scientist 2,$52K - $95K (Glassdoor est.),Description\nDigital Health and Analytics with...,3.9,Humana3.9,"Louisville, KY",-1,-1,-1,-1,-1,-1,-1,-1
2,Data Scientist 2,$52K - $95K (Glassdoor est.),Description\nDigital Health and Analytics with...,3.9,Humana3.9,"Louisville, KY",-1,-1,-1,-1,-1,-1,-1,-1
3,Data Scientist 2,$52K - $95K (Glassdoor est.),Description\nDigital Health and Analytics with...,3.9,Humana3.9,"Louisville, KY",-1,-1,-1,-1,-1,-1,-1,-1
4,Data Scientist 2,$52K - $95K (Glassdoor est.),Description\nDigital Health and Analytics with...,3.9,Humana3.9,"Louisville, KY",-1,-1,-1,-1,-1,-1,-1,-1
5,Data Scientist 2,$52K - $95K (Glassdoor est.),Description\nDigital Health and Analytics with...,3.9,Humana3.9,"Louisville, KY",-1,-1,-1,-1,-1,-1,-1,-1
6,Data Scientist 2,$52K - $95K (Glassdoor est.),Description\nDigital Health and Analytics with...,3.9,Humana3.9,"Louisville, KY",-1,-1,-1,-1,-1,-1,-1,-1
7,Data Scientist 2,$52K - $95K (Glassdoor est.),Description\nDigital Health and Analytics with...,3.9,Humana3.9,"Louisville, KY",-1,-1,-1,-1,-1,-1,-1,-1
8,Data Scientist 2,$52K - $95K (Glassdoor est.),Description\nDigital Health and Analytics with...,3.9,Humana3.9,"Louisville, KY",-1,-1,-1,-1,-1,-1,-1,-1
9,Data Scientist 2,$52K - $95K (Glassdoor est.),Description\nDigital Health and Analytics with...,3.9,Humana3.9,"Louisville, KY",-1,-1,-1,-1,-1,-1,-1,-1